Ansible 1
Otus-DevOps-2023-07/dmitriy-kutepow_infra pull request #6
Opened 2023-09-19 10:02 UTC by dmitriy-kutepow

# Выполнено ДЗ №8

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
1.Установлен Ansible
2.Запущены VMs appserver и dbserver с помощью terraform
3.Создан инвентори файл ansible/inventory
4.Выполнена команда ping для хостов appserver и dbserver
5.Установлены значения по умолчанию в конфигурационном файле ансибла ansible/ansible.cfg
6.Проверена работу команд 'ruby -v' и 'bundler -v' на соответствующих хостах
7.Написан и проверен простой плейбук ansible/clone.yml

## Как запустить проект:
 - выполнить команду terraform apply

## Как проверить работоспособность:
 - Выполнить команды из README.md

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-09-19 10:03 UTC, dmitriy-kutepow commented
Почему-то .gitignore не работает....

2023-09-19 14:16 UTC, mrgreyves commented
> Почему-то .gitignore не работает....

Здравствуйте!
Скорее всего не правильно указаны пути для файлов
Так же у вас где пропали тесты =(

2023-09-19 14:17 UTC, mrgreyves requested changes
Здравствуйте!)
ДЗ нужно выполнять в этом же репозитории, в отдельной ветке
Про гитигнор так же написал
ДЗ возвращаю на доработку

2023-09-20 08:33 UTC, dmitriy-kutepow commented
Чёт ерунду я через visual studio наворотил))))

2023-09-20 08:43 UTC, closed without merging