Ansible 2
Otus-DevOps-2023-07/dmitriy-kutepow_infra pull request #9
Opened 2023-09-25 10:40 UTC by dmitriy-kutepow

# Выполнено ДЗ №9

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
1. Использовал плейбуки, хендлеры и шаблоны для конфигурации окружения и деплоя тестового приложения. Подход один плейбук, один сценарий (play)
2. Использовал один плейбук, но много сценариев
3. Использовал много плейбуков.
4. Изменил провижн образов Packer на Ansible-плейбуки
5. Протестировал на stage окружении.

## Как запустить проект:
 - Собрать базовые образы пакером
 - Запустить стейдж окружение терраформом
 - Обновить конфигурацию ансиблом
 Команды использованые в процессе выполнения работы хранятся в README.md

## Как проверить работоспособность:
 - Перейти по ссылке http://app-ip-addres:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2023-09-26 20:34 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Вам нужно добавить или перенести фейковый ключик для пакера
Приключение минут на 10 =)
ДЗ возвращаю на доработку

2023-09-27 12:00 UTC, dmitriy-kutepow commented
Странно, а в какой папке он его ожидает? Он лежит в папке packer/fake_key.json, странно, до этогож работало..... Поправил.

2023-09-28 20:44 UTC, mrgreyves requested changes
Зддравствуйте
Оставил комментарий к файлу
Нужно немного поправить =)

2023-09-28 20:44 UTC, mrgreyves commented on packer/app.json
> +            "use_proxy": "false"
Сейчас ругается что не знает этот параметр
Попробуйте удалить =)

2023-10-12 11:19 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)
ДЗ принимаю =)

2023-10-15 11:24 UTC, merged